language: python

python:
  - 3.6

cache: pip

services:
  - docker

install:
  - pip install -U codecov
  - pip install -r requirements.txt

script:
  - bash tests/test-with-compose.sh

after_success:
  - codecov
